
// Real Client store and scheme definitions synced with rules engine & catalog
export const INITIAL_SCHEMES = [
  {
    id: 'pmkisan',
    name: 'PM-KISAN',
    fullName: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    sectorType: 'CENTRAL',
    benefit_amount: '₹6,000 / year',
    benefitShort: '₹6,000 / year',
    benefitDetail: 'Direct income support of ₹6,000 per year to farmer families in three equal installments of ₹2,000 directly into bank accounts.',
    applyUrl: 'https://pmkisan.gov.in',
    apply_url: 'https://pmkisan.gov.in',
    qualifications: [
      { text: 'Farmer with agricultural land', sub: 'Cultivable landholding in your name.' },
      { text: 'Not an income tax payer', sub: 'You have not filed income tax in last assessment year.' },
      { text: 'Not a government employee', sub: 'No serving/retired government officer in household.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Bank Account (DBT)', status: 'Linked to Aadhaar' },
      { name: 'Land Record (Khasra/Khatauni)', status: 'Revenue dept. copy' }
    ],
    officialEligibility: {
      description: 'All landholding farmers families, which have cultivable landholding in their names are eligible to get benefit under the scheme.',
      exclusions: 'Institutional landholders, farmer families holding constitutional posts, serving/retired officers and employees of state/central government, professionals, and persons who paid income tax in the last assessment year.'
    }
  },
  {
    id: 'pmfby',
    name: 'PM Fasal Bima Yojana',
    fullName: 'Pradhan Mantri Fasal Bima Yojana',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    sectorType: 'CENTRAL',
    benefit_amount: 'Comprehensive Crop Insurance',
    benefitShort: '2% Kharif / 1.5% Rabi',
    benefitDetail: 'Financial support and comprehensive risk insurance against non-preventable natural risks from pre-sowing to post-harvest.',
    applyUrl: 'https://pmfby.gov.in',
    apply_url: 'https://pmfby.gov.in',
    qualifications: [
      { text: 'Farmer with notified crop', sub: 'Cultivating crops covered under seasonal notification.' },
      { text: 'Valid land holding', sub: 'Owner or recorded tenant farmer.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Land Record / Khasra', status: 'Required' },
      { name: 'Sowing Certificate', status: 'From Patwari' },
      { name: 'Bank Passbook', status: 'Active' }
    ],
    officialEligibility: {
      description: 'All farmers including sharecroppers and tenant farmers growing the notified crops in the notified areas are eligible for coverage.',
      exclusions: 'Crops not covered under the state insurance notification for the current season.'
    }
  },
  {
    id: 'kcc',
    name: 'Kisan Credit Card',
    fullName: 'Kisan Credit Card (KCC) Scheme',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'agriculture',
    sectorType: 'CENTRAL',
    benefit_amount: 'Credit up to ₹3 Lakh at 4% interest',
    benefitShort: '₹3 Lakh / 4% interest',
    benefitDetail: 'Timely access to affordable credit for farmers to meet agriculture inputs and allied activities.',
    applyUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    apply_url: 'https://www.myscheme.gov.in/schemes/kcc',
    qualifications: [
      { text: 'Owner cultivators or tenant farmers', sub: 'Engaged in agricultural cultivation or allied activities.' },
      { text: 'Valid identification & land records', sub: 'Verified identity and cultivation proof.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Land Record & Cropping Pattern', status: 'Revenue record' },
      { name: 'Passport Photograph', status: 'Required' }
    ],
    officialEligibility: {
      description: 'All farmers, individual/joint borrowers, tenant farmers, oral lessees, and sharecroppers.',
      exclusions: 'Defaulting borrowers on institutional agricultural loans.'
    }
  },
  {
    id: 'pmksy',
    name: 'PM Krishi Sinchayee Yojana',
    fullName: 'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    ministry: 'Ministry of Jal Shakti / Agriculture',
    category: 'agriculture',
    sectorType: 'CENTRAL',
    benefit_amount: 'Up to 55% Micro-Irrigation Subsidy',
    benefitShort: 'Up to 55% / Subsidy',
    benefitDetail: 'Expands cultivable area under assured irrigation, improves on-farm water use efficiency ("Per Drop More Crop").',
    applyUrl: 'https://pmksy.gov.in',
    apply_url: 'https://pmksy.gov.in',
  },
  {
    id: 'pmayg',
    name: 'PMAY-G',
    fullName: 'Pradhan Mantri Awas Yojana - Gramin',
    ministry: 'Ministry of Rural Development',
    category: 'housing',
    sectorType: 'CENTRAL',
    benefit_amount: 'Up to ₹1.30 Lakh + Toilet grant',
    benefitShort: '₹1.30 Lakh / unit',
    benefitDetail: 'Financial assistance to homeless and kutcha house dwellers in rural areas to construct pucca houses with basic amenities.',
    applyUrl: 'https://pmayg.nic.in',
    apply_url: 'https://pmayg.nic.in',
    qualifications: [
      { text: 'Rural residency confirmed', sub: 'Living in a designated rural panchayat.' },
      { text: 'No existing pucca house', sub: 'Kutcha roof / temporary dwelling reported.' },
      { text: 'Income within BPL limits', sub: 'Family income meets SECC 2011 criteria.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Bank Account Details (DBT)', status: 'DBT enabled' },
      { name: 'BPL / SECC 2011 Record', status: 'Panchayat list' }
    ],
    officialEligibility: {
      description: 'Homeless families and families living in kutcha and dilapidated houses in rural areas.',
      exclusions: 'Households owning motorized vehicles, mechanized agricultural equipment, or with a government employee earning above ₹10,000/month.'
    }
  },
  {
    id: 'pmayu',
    name: 'PM Awas Yojana - Urban',
    fullName: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'housing',
    sectorType: 'CENTRAL',
    benefit_amount: 'Up to ₹2.67 Lakh Interest Subsidy',
    benefitShort: 'Up to ₹2.67 Lakh / Subsidy',
    benefitDetail: 'Credit-linked subsidy scheme on home loans for economically weaker sections (EWS) and lower income groups (LIG).',
    applyUrl: 'https://pmay-urban.gov.in',
    apply_url: 'https://pmay-urban.gov.in',
  },
  {
    id: 'pmjay',
    name: 'Ayushman Bharat PM-JAY',
    fullName: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    sectorType: 'CENTRAL',
    benefit_amount: '₹5 Lakh / family / year',
    benefitShort: '₹5,00,000 / family / year',
    benefitDetail: 'Cashless and paperless access to secondary and tertiary healthcare services across empanelled public and private hospitals.',
    applyUrl: 'https://beneficiary.nha.gov.in',
    apply_url: 'https://beneficiary.nha.gov.in',
    qualifications: [
      { text: 'Low-income household', sub: 'Annual family income below threshold.' },
      { text: 'Included in SECC / NFSA database', sub: 'Eligible beneficiary category.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Ration Card', status: 'For family identification' }
    ],
    officialEligibility: {
      description: 'Bottom 40% vulnerable population identified by SECC 2011 database.',
      exclusions: 'Households with high income or motorized 4-wheelers.'
    }
  },
  {
    id: 'ayushman',
    name: 'Ayushman Bharat PM-JAY',
    fullName: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    sectorType: 'CENTRAL',
    benefit_amount: '₹5 Lakh / family / year',
    benefitShort: '₹5,00,000 / family / year',
    benefitDetail: 'Cashless and paperless access to secondary and tertiary healthcare services across empanelled public and private hospitals.',
    applyUrl: 'https://beneficiary.nha.gov.in',
    apply_url: 'https://beneficiary.nha.gov.in',
  },
  {
    id: 'pmsby',
    name: 'PM Suraksha Bima Yojana',
    fullName: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    ministry: 'Ministry of Finance',
    category: 'health',
    sectorType: 'CENTRAL',
    benefit_amount: '₹2 Lakh Accidental Cover for ₹20/year',
    benefitShort: '₹2,00,000 / accidental cover',
    benefitDetail: 'Accident insurance providing ₹2 Lakh coverage for accidental death and permanent disability at ₹20/year.',
    applyUrl: 'https://www.jansuraksha.gov.in',
    apply_url: 'https://www.jansuraksha.gov.in',
  },
  {
    id: 'svanidhi',
    name: 'PM SVANidhi',
    fullName: 'Prime Minister Street Vendor\'s AtmaNirbhar Nidhi',
    ministry: 'Ministry of Housing & Urban Affairs',
    category: 'business',
    sectorType: 'CENTRAL',
    benefit_amount: 'Collateral-free loan up to ₹50,000',
    benefitShort: '₹10,000 - ₹50,000 / loan',
    benefitDetail: 'Affordable working capital loan up to ₹10,000 for 1st tranche, followed by ₹20,000 and ₹50,000 for timely repayment.',
    applyUrl: 'https://pmsvanidhi.mohua.gov.in',
    apply_url: 'https://pmsvanidhi.mohua.gov.in',
    qualifications: [
      { text: 'Street vendor in urban area', sub: 'Vending identity card or letter of recommendation from ULB.' }
    ],
    requiredDocs: [
      { name: 'Aadhaar Card', status: 'Pre-verified' },
      { name: 'Vending Certificate', status: 'Municipal ID' },
      { name: 'Bank Account', status: 'Active' }
    ],
    officialEligibility: {
      description: 'Street vendors engaged in vending in urban areas on or before March 24, 2020.',
      exclusions: 'Non-urban vendors without valid recommendation certificate.'
    }
  },
  {
    id: 'mudra',
    name: 'Pradhan Mantri MUDRA Yojana',
    fullName: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    ministry: 'Ministry of Finance',
    category: 'business',
    sectorType: 'CENTRAL',
    benefit_amount: 'Loans up to ₹10 Lakh (Shishu, Kishore, Tarun)',
    benefitShort: 'Up to ₹10 Lakh / Loan',
    benefitDetail: 'Collateral-free funding for micro and small non-corporate, non-farm enterprises.',
    applyUrl: 'https://www.udyamimitra.in',
    apply_url: 'https://www.udyamimitra.in',
  },
  {
    id: 'mgnregs',
    name: 'Mahatma Gandhi NREGS',
    fullName: 'Mahatma Gandhi National Rural Employment Guarantee Scheme',
    ministry: 'Ministry of Rural Development',
    category: 'employment',
    sectorType: 'CENTRAL',
    benefit_amount: '100 days Guaranteed Wage Employment',
    benefitShort: '100 days / year',
    benefitDetail: 'Legal guarantee for at least 100 days of wage employment in every financial year to adult members of any rural household.',
    applyUrl: 'https://nrega.nic.in',
    apply_url: 'https://nrega.nic.in',
  },
  {
    id: 'pmkvy',
    name: 'PM Kaushal Vikas Yojana 4.0',
    fullName: 'Pradhan Mantri Kaushal Vikas Yojana 4.0',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    category: 'skill',
    sectorType: 'CENTRAL',
    benefit_amount: 'Free Industry Skill Training + Certification + ₹8,000',
    benefitShort: 'Free Training + ₹8,000',
    benefitDetail: 'Skill certification scheme to enable Indian youth to take up industry-relevant skill training for better livelihoods.',
    applyUrl: 'https://www.skillindiadigital.gov.in',
    apply_url: 'https://www.skillindiadigital.gov.in',
  },
  {
    id: 'pm_vishwakarma',
    name: 'PM Vishwakarma Scheme',
    fullName: 'PM Vishwakarma Scheme for Artisans & Craftspeople',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'skill',
    sectorType: 'CENTRAL',
    benefit_amount: '₹15,000 Toolkit + Loan up to ₹3 Lakh at 5%',
    benefitShort: '₹15,000 Toolkit + ₹3L Loan',
    benefitDetail: 'Comprehensive support to traditional artisans and craftspeople including recognition, skill upgradation, toolkit incentive, and credit.',
    applyUrl: 'https://pmvishwakarma.gov.in',
    apply_url: 'https://pmvishwakarma.gov.in',
  },
  {
    id: 'pmvishwakarma',
    name: 'PM Vishwakarma Scheme',
    fullName: 'PM Vishwakarma Scheme for Artisans & Craftspeople',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'skill',
    sectorType: 'CENTRAL',
    benefit_amount: '₹15,000 Toolkit + Loan up to ₹3 Lakh at 5%',
    benefitShort: '₹15,000 Toolkit + ₹3L Loan',
    benefitDetail: 'Comprehensive support to traditional artisans and craftspeople including recognition, skill upgradation, toolkit incentive, and credit.',
    applyUrl: 'https://pmvishwakarma.gov.in',
    apply_url: 'https://pmvishwakarma.gov.in',
  },
  {
    id: 'sukanya_samriddhi',
    name: 'Sukanya Samriddhi Yojana',
    fullName: 'Sukanya Samriddhi Yojana (SSY)',
    ministry: 'Ministry of Finance',
    category: 'social',
    sectorType: 'CENTRAL',
    benefit_amount: 'High 8.2% Interest + Tax Exemption under 80C',
    benefitShort: '8.2% Interest / Tax-free',
    benefitDetail: 'Small deposit savings scheme targeted for girl child education and marriage expenses.',
    applyUrl: 'https://www.myscheme.gov.in/schemes/ssy',
    apply_url: 'https://www.myscheme.gov.in/schemes/ssy',
  },
  {
    id: 'ssy',
    name: 'Sukanya Samriddhi Yojana',
    fullName: 'Sukanya Samriddhi Yojana (SSY)',
    ministry: 'Ministry of Finance',
    category: 'social',
    sectorType: 'CENTRAL',
    benefit_amount: 'High 8.2% Interest + Tax Exemption under 80C',
    benefitShort: '8.2% Interest / Tax-free',
    benefitDetail: 'Small deposit savings scheme targeted for girl child education and marriage expenses.',
    applyUrl: 'https://www.myscheme.gov.in/schemes/ssy',
    apply_url: 'https://www.myscheme.gov.in/schemes/ssy',
    qualifications: [
      { text: 'Girl child below 10 years', sub: 'Account opened by parent or legal guardian.' },
      { text: 'One account per girl child', sub: 'Maximum 2 accounts per family.' },
    ],
    requiredDocs: ['Birth certificate of girl child', 'Identity proof of guardian', 'Address proof', 'Passport-size photograph'],
  },
  {
    id: 'pmjjby',
    name: 'PMJJBY',
    fullName: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    ministry: 'Ministry of Finance',
    category: 'social',
    sectorType: 'CENTRAL',
    benefit_amount: '₹2 Lakh life cover at ₹436/year',
    benefitShort: '₹2 Lakh life insurance',
    benefitDetail: 'Affordable life insurance scheme providing ₹2 lakh cover on death for just ₹436 per year premium.',
    applyUrl: 'https://www.jansuraksha.gov.in',
    apply_url: 'https://www.jansuraksha.gov.in',
    qualifications: [
      { text: 'Age 18 to 50 years', sub: 'Renewable up to age 55.' },
      { text: 'Must have a bank/post office account', sub: 'Auto-debit of premium from savings account.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Bank account details', 'PMJJBY enrollment form'],
  },
  {
    id: 'nsp_sc',
    name: 'CSSS Scholarship',
    fullName: 'Central Sector Scheme of Scholarships (CSSS)',
    ministry: 'Ministry of Education',
    category: 'education',
    sectorType: 'CENTRAL',
    benefit_amount: '₹10,000–20,000 / year',
    benefitShort: 'Up to ₹20,000/year',
    benefitDetail: 'Merit-based scholarship for students from low-income families who scored 80th+ percentile in 12th board exam.',
    applyUrl: 'https://scholarships.gov.in',
    apply_url: 'https://scholarships.gov.in',
    qualifications: [
      { text: '80th percentile or above in Class 12 Board exams', sub: 'Must be in top 20% of successful candidates.' },
      { text: 'Family income below ₹8 lakh/year', sub: 'Applicable for undergraduate students.' },
      { text: 'Regular college/university student', sub: 'Not applicable for distance learning.' },
    ],
    requiredDocs: ['Class 12 marksheet', 'Income certificate', 'Aadhaar Card', 'College admission receipt', 'Bank passbook', 'Caste certificate (if applicable)'],
  },
  {
    id: 'nsp_obc',
    name: 'OBC Pre-Matric Scholarship',
    fullName: 'Pre-Matric Scholarship for OBC Students',
    ministry: 'Ministry of Social Justice & Empowerment',
    category: 'education',
    sectorType: 'CENTRAL',
    benefit_amount: '₹1,000–10,000 / year',
    benefitShort: 'Up to ₹10,000/year',
    benefitDetail: 'Scholarship for OBC students in Class 9-10 to support their pre-matric education and reduce dropout rates.',
    applyUrl: 'https://scholarships.gov.in',
    apply_url: 'https://scholarships.gov.in',
    qualifications: [
      { text: 'OBC category student in Class 9 or 10', sub: 'Valid OBC certificate required.' },
      { text: 'Family income below ₹2.5 lakh/year', sub: 'Income certificate from competent authority.' },
    ],
    requiredDocs: ['OBC certificate', 'Income certificate', 'Aadhaar Card', 'School enrollment certificate', 'Previous year marksheet', 'Bank passbook'],
  },
  {
    id: 'pmmatru',
    name: 'PMMVY',
    fullName: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    sectorType: 'CENTRAL',
    benefit_amount: '₹5,000 maternity benefit',
    benefitShort: '₹5,000 for first child',
    benefitDetail: 'Maternity benefit of ₹5,000 in installments for the first live birth, to support pregnant women and lactating mothers.',
    applyUrl: 'https://pmmvy.wcd.gov.in',
    apply_url: 'https://pmmvy.wcd.gov.in',
    qualifications: [
      { text: 'Pregnant woman 19 years or older', sub: 'Applicable for first live birth.' },
      { text: 'Not a central/state government employee', sub: 'Private and informal sector workers eligible.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Bank account linked to Aadhaar', 'MCP (Mother & Child Protection) card', 'Proof of pregnancy (from ANM/doctor)'],
  },
  {
    id: 'bbbp',
    name: 'Beti Bachao Beti Padhao',
    fullName: 'Beti Bachao Beti Padhao (BBBP)',
    ministry: 'Ministry of Women & Child Development',
    category: 'women',
    sectorType: 'CENTRAL',
    benefit_amount: 'Education support + awareness campaigns',
    benefitShort: 'Girl child education',
    benefitDetail: 'Scheme to address declining child sex ratio, promote girl child education, and prevent gender-biased sex selective elimination.',
    applyUrl: 'https://wcd.nic.in/bbbp-schemes',
    apply_url: 'https://wcd.nic.in/bbbp-schemes',
    qualifications: [
      { text: 'Families with girl child in targeted districts', sub: 'Implemented in 640 districts.' },
    ],
    requiredDocs: ['Birth certificate of girl child', 'Aadhaar Card'],
  },
  {
    id: 'pmuy',
    name: 'PM Ujjwala Yojana',
    fullName: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    ministry: 'Ministry of Petroleum & Natural Gas',
    category: 'welfare',
    sectorType: 'CENTRAL',
    benefit_amount: 'Free LPG connection + ₹1,600 subsidy',
    benefitShort: 'Free LPG connection',
    benefitDetail: 'Provides free LPG gas connections to women from Below Poverty Line households to replace polluting fuels.',
    applyUrl: 'https://pmuy.gov.in',
    apply_url: 'https://pmuy.gov.in',
    qualifications: [
      { text: 'Adult woman from BPL household', sub: 'Name must appear in SECC 2011 or ration card.' },
      { text: 'No existing LPG connection at home', sub: 'Must not be registered LPG user.' },
    ],
    requiredDocs: ['BPL ration card / SECC 2011 data', 'Aadhaar Card', 'Bank passbook', 'Passport-size photograph'],
  },
  {
    id: 'pmjdy',
    name: 'PM Jan Dhan Yojana',
    fullName: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    ministry: 'Ministry of Finance',
    category: 'finance',
    sectorType: 'CENTRAL',
    benefit_amount: 'Zero-balance account + ₹2 lakh accident cover + ₹30,000 life cover',
    benefitShort: 'Free bank account + insurance',
    benefitDetail: 'Universal banking access with zero-balance accounts, RuPay debit cards, overdraft facility, and insurance coverage.',
    applyUrl: 'https://pmjdy.gov.in',
    apply_url: 'https://pmjdy.gov.in',
    qualifications: [
      { text: 'Any Indian citizen without a bank account', sub: 'No minimum balance required.' },
      { text: 'Minimum age 10 years', sub: 'Minors can open jointly with guardian.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Passport-size photograph', 'Mobile number'],
  },
  {
    id: 'apy',
    name: 'Atal Pension Yojana',
    fullName: 'Atal Pension Yojana (APY)',
    ministry: 'Ministry of Finance (PFRDA)',
    category: 'social',
    sectorType: 'CENTRAL',
    benefit_amount: '₹1,000–5,000/month pension after 60',
    benefitShort: '₹1,000–5,000/month pension',
    benefitDetail: 'Pension scheme for unorganised sector workers. Government co-contributes 50% or ₹1,000/year for 5 years for eligible subscribers.',
    applyUrl: 'https://www.npscra.nsdl.co.in',
    apply_url: 'https://www.npscra.nsdl.co.in',
    qualifications: [
      { text: 'Age 18 to 40 years', sub: 'Pension starts at age 60.' },
      { text: 'Must have a savings bank account', sub: 'Linked to Aadhaar and mobile.' },
      { text: 'Not an income tax payer (for govt co-contribution)', sub: 'All citizens can subscribe regardless.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Bank account passbook', 'Mobile number'],
  },
  {
    id: 'standup',
    name: 'Stand-Up India',
    fullName: 'Stand-Up India Scheme',
    ministry: 'Ministry of Finance (SIDBI)',
    category: 'enterprise',
    sectorType: 'CENTRAL',
    benefit_amount: 'Loans ₹10 lakh to ₹1 crore',
    benefitShort: '₹10L–1Cr bank loan',
    benefitDetail: 'Bank loans between ₹10 lakh and ₹1 crore to at least one SC/ST borrower and one woman borrower per bank branch for greenfield enterprises.',
    applyUrl: 'https://www.standupmitra.in',
    apply_url: 'https://www.standupmitra.in',
    qualifications: [
      { text: 'SC/ST or Woman entrepreneur', sub: 'For setting up a greenfield enterprise.' },
      { text: 'Age 18+ years', sub: 'For non-individual enterprises: 51%+ stake of SC/ST or woman.' },
    ],
    requiredDocs: ['Aadhaar Card', 'PAN Card', 'Caste certificate (for SC/ST)', 'Business plan', 'Bank account details', 'Address proof'],
  },
  {
    id: 'nhm_jssk',
    name: 'Janani Shishu Suraksha Karyakram',
    fullName: 'Janani Shishu Suraksha Karyakram (JSSK)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    sectorType: 'CENTRAL',
    benefit_amount: 'Free delivery + free medicines + free transport',
    benefitShort: 'Free maternity care',
    benefitDetail: 'Free and cashless services for pregnant women and sick newborns at public health institutions including free transport, diagnosis, medicines, and food.',
    applyUrl: 'https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309',
    apply_url: 'https://nhm.gov.in',
    qualifications: [
      { text: 'All pregnant women', sub: 'At government hospitals / PHCs.' },
      { text: 'Sick newborns up to 30 days after birth', sub: 'At public health institutions.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Antenatal card / MCP card'],
  },
  {
    id: 'ddugky',
    name: 'DDU-GKY',
    fullName: 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
    ministry: 'Ministry of Rural Development',
    category: 'skill',
    sectorType: 'CENTRAL',
    benefit_amount: 'Free skill training + ₹500–3,000/month stipend + job placement',
    benefitShort: 'Free training + job placement',
    benefitDetail: 'Skill training and placement programme for rural poor youth to provide sustainable employment in organized sectors.',
    applyUrl: 'https://ddugky.gov.in',
    apply_url: 'https://ddugky.gov.in',
    qualifications: [
      { text: 'Age 15 to 35 years (45 for special groups)', sub: 'SC/ST/women/differently-abled get relaxation.' },
      { text: 'From a rural poor household', sub: 'As per SECC 2011 data.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Age proof', 'Income/BPL certificate', 'Educational certificate', 'Passport-size photograph'],
  },
  {
    id: 'abua_awas',
    name: 'Abua Awas Yojana',
    fullName: 'Abua Awas Yojana (Jharkhand)',
    ministry: 'Government of Jharkhand',
    category: 'housing',
    sectorType: 'STATE',
    benefit_amount: '₹2 Lakh for housing construction',
    benefitShort: '₹2 Lakh housing grant',
    benefitDetail: 'State housing scheme by Jharkhand government providing ₹2 lakh to homeless and kutcha house dwellers for construction of pucca houses.',
    applyUrl: 'https://abuaawasyojana.jharkhand.gov.in',
    apply_url: 'https://abuaawasyojana.jharkhand.gov.in',
    qualifications: [
      { text: 'Jharkhand resident', sub: 'Domicile certificate required.' },
      { text: 'Homeless or living in kutcha house', sub: 'No existing pucca house.' },
      { text: 'Not a beneficiary of PMAY-G', sub: 'Must not have received central housing benefit.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Domicile certificate', 'Bank passbook', 'Land ownership document'],
  },
  {
    id: 'nrlm',
    name: 'DAY-NRLM (SHG)',
    fullName: 'Deendayal Antyodaya Yojana – National Rural Livelihoods Mission',
    ministry: 'Ministry of Rural Development',
    category: 'enterprise',
    sectorType: 'CENTRAL',
    benefit_amount: 'Revolving fund ₹15,000 + loans up to ₹3 lakh at 7% interest',
    benefitShort: 'SHG loans at 7% interest',
    benefitDetail: 'Supports rural poor women through Self-Help Groups (SHGs) with revolving funds, low-interest bank linkages, and livelihood support.',
    applyUrl: 'https://aajeevika.gov.in',
    apply_url: 'https://aajeevika.gov.in',
    qualifications: [
      { text: 'Rural poor woman', sub: 'Must be part of or willing to form an SHG.' },
      { text: 'Household income below poverty line preferred', sub: 'Priority to SC/ST, minorities, differently-abled.' },
    ],
    requiredDocs: ['Aadhaar Card', 'Bank account passbook', 'SHG registration certificate', 'Passport-size photograph'],
  },
  {
    id: 'nhps',
    name: 'National Health Protection Scheme',
    fullName: 'Ayushman Bharat – Health & Wellness Centres',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'health',
    sectorType: 'CENTRAL',
    benefit_amount: 'Free primary healthcare services at HWC',
    benefitShort: 'Free primary health care',
    benefitDetail: 'Free comprehensive primary healthcare services including NCD screening, maternal care, mental health, and emergency services at Health & Wellness Centres.',
    applyUrl: 'https://nhm.gov.in',
    apply_url: 'https://nhm.gov.in',
    qualifications: [
      { text: 'All citizens', sub: 'Universal access at Health & Wellness Centres.' },
    ],
    requiredDocs: ['Aadhaar Card or any ID proof'],
  },
];

// Returns ONLY real submitted applications
export function getApplications() {
  const stored = localStorage.getItem('jansetu_applications');
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      if (Array.isArray(parsed)) return parsed;
    } catch {
      return [];
    }
  }
  return [];
}

export function saveApplication(app) {
  const current = getApplications();
  const updated = [app, ...current.filter(a => a.id !== app.id)];
  localStorage.setItem('jansetu_applications', JSON.stringify(updated));
  return updated;
}
